/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) spin_model_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {24, 1, 1};
static const casadi_int casadi_s5[3] = {8, 1, 1};
static const casadi_int casadi_s6[22] = 
  {7, 8, 0, 1, 2, 3, 4, 5,
  6, 7, 11, 2, 3, 4, 5, 6,
  0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[3] = {8, 0, 1};

/* spin_model_cost_y_0_fun_jac_ut_xt:(i0[5],i1[2],i2[0],i3[],i4[24])->(o0[8],o1[7x8,11nz],o2[8x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102, a103, a104, a105;
  a000=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a000;
  a001=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a001;
  a002=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a002;
  a003=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a003;
  a004=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a004;
  a004=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][5]=a004;
  a004=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][6]=a004;
  a004=arg[4]? arg[4][0] : 0;
  a004=(a000-a004);
  a005=cos(a002);
  a006=(a004*a005);
  a007=arg[4]? arg[4][1] : 0;
  a007=(a001-a007);
  a002=sin(a002);
  a008=(a007*a002);
  a009=(a006+a008);
  a010=5.0000000000000000e-01;
  a011=9.9999999999999978e-02;
  a012=casadi_fabs(a003);
  a013=(a011*a012);
  a014=casadi_fmin(a013,a011);
  a010=(a010+a014);
  a014=arg[4]? arg[4][2] : 0;
  a015=(a010+a014);
  a009=(a009/a015);
  a016=casadi_sq(a009);
  a017=casadi_sq(a016);
  a007=(a007*a005);
  a004=(a004*a002);
  a007=(a007-a004);
  a004=2.9999999999999999e-01;
  a018=1.0000000000000003e-01;
  a012=(a018*a012);
  a019=casadi_fmin(a012,a018);
  a004=(a004+a019);
  a014=(a004+a014);
  a019=(a007/a014);
  a020=casadi_sq(a019);
  a021=casadi_sq(a020);
  a017=(a017+a021);
  a021=1.0000000000000000e-04;
  a017=(a017+a021);
  a022=(1./a017);
  a023=arg[4]? arg[4][3] : 0;
  a023=(a000-a023);
  a024=(a023*a005);
  a025=arg[4]? arg[4][4] : 0;
  a025=(a001-a025);
  a026=(a025*a002);
  a027=(a024+a026);
  a028=arg[4]? arg[4][5] : 0;
  a029=(a010+a028);
  a027=(a027/a029);
  a030=casadi_sq(a027);
  a031=casadi_sq(a030);
  a025=(a025*a005);
  a023=(a023*a002);
  a025=(a025-a023);
  a028=(a004+a028);
  a023=(a025/a028);
  a032=casadi_sq(a023);
  a033=casadi_sq(a032);
  a031=(a031+a033);
  a031=(a031+a021);
  a033=(1./a031);
  a034=(a022+a033);
  a035=arg[4]? arg[4][6] : 0;
  a035=(a000-a035);
  a036=(a035*a005);
  a037=arg[4]? arg[4][7] : 0;
  a037=(a001-a037);
  a038=(a037*a002);
  a039=(a036+a038);
  a040=arg[4]? arg[4][8] : 0;
  a041=(a010+a040);
  a039=(a039/a041);
  a042=casadi_sq(a039);
  a043=casadi_sq(a042);
  a037=(a037*a005);
  a035=(a035*a002);
  a037=(a037-a035);
  a040=(a004+a040);
  a035=(a037/a040);
  a044=casadi_sq(a035);
  a045=casadi_sq(a044);
  a043=(a043+a045);
  a043=(a043+a021);
  a045=(1./a043);
  a034=(a034+a045);
  a046=arg[4]? arg[4][9] : 0;
  a046=(a000-a046);
  a047=(a046*a005);
  a048=arg[4]? arg[4][10] : 0;
  a048=(a001-a048);
  a049=(a048*a002);
  a050=(a047+a049);
  a051=arg[4]? arg[4][11] : 0;
  a052=(a010+a051);
  a050=(a050/a052);
  a053=casadi_sq(a050);
  a054=casadi_sq(a053);
  a048=(a048*a005);
  a046=(a046*a002);
  a048=(a048-a046);
  a051=(a004+a051);
  a046=(a048/a051);
  a055=casadi_sq(a046);
  a056=casadi_sq(a055);
  a054=(a054+a056);
  a054=(a054+a021);
  a056=(1./a054);
  a034=(a034+a056);
  a057=arg[4]? arg[4][12] : 0;
  a057=(a000-a057);
  a058=(a057*a005);
  a059=arg[4]? arg[4][13] : 0;
  a059=(a001-a059);
  a060=(a059*a002);
  a061=(a058+a060);
  a062=arg[4]? arg[4][14] : 0;
  a063=(a010+a062);
  a061=(a061/a063);
  a064=casadi_sq(a061);
  a065=casadi_sq(a064);
  a059=(a059*a005);
  a057=(a057*a002);
  a059=(a059-a057);
  a062=(a004+a062);
  a057=(a059/a062);
  a066=casadi_sq(a057);
  a067=casadi_sq(a066);
  a065=(a065+a067);
  a065=(a065+a021);
  a067=(1./a065);
  a034=(a034+a067);
  a068=arg[4]? arg[4][15] : 0;
  a068=(a000-a068);
  a069=(a068*a005);
  a070=arg[4]? arg[4][16] : 0;
  a070=(a001-a070);
  a071=(a070*a002);
  a072=(a069+a071);
  a073=arg[4]? arg[4][17] : 0;
  a074=(a010+a073);
  a072=(a072/a074);
  a075=casadi_sq(a072);
  a076=casadi_sq(a075);
  a070=(a070*a005);
  a068=(a068*a002);
  a070=(a070-a068);
  a073=(a004+a073);
  a068=(a070/a073);
  a077=casadi_sq(a068);
  a078=casadi_sq(a077);
  a076=(a076+a078);
  a076=(a076+a021);
  a078=(1./a076);
  a034=(a034+a078);
  a079=arg[4]? arg[4][18] : 0;
  a079=(a000-a079);
  a080=(a079*a005);
  a081=arg[4]? arg[4][19] : 0;
  a081=(a001-a081);
  a082=(a081*a002);
  a083=(a080+a082);
  a084=arg[4]? arg[4][20] : 0;
  a085=(a010+a084);
  a083=(a083/a085);
  a086=casadi_sq(a083);
  a087=casadi_sq(a086);
  a081=(a081*a005);
  a079=(a079*a002);
  a081=(a081-a079);
  a084=(a004+a084);
  a079=(a081/a084);
  a088=casadi_sq(a079);
  a089=casadi_sq(a088);
  a087=(a087+a089);
  a087=(a087+a021);
  a089=(1./a087);
  a034=(a034+a089);
  a090=arg[4]? arg[4][21] : 0;
  a000=(a000-a090);
  a090=(a000*a005);
  a091=arg[4]? arg[4][22] : 0;
  a001=(a001-a091);
  a091=(a001*a002);
  a092=(a090+a091);
  a093=arg[4]? arg[4][23] : 0;
  a010=(a010+a093);
  a092=(a092/a010);
  a094=casadi_sq(a092);
  a095=casadi_sq(a094);
  a001=(a001*a005);
  a000=(a000*a002);
  a001=(a001-a000);
  a004=(a004+a093);
  a093=(a001/a004);
  a000=casadi_sq(a093);
  a096=casadi_sq(a000);
  a095=(a095+a096);
  a095=(a095+a021);
  a021=(1./a095);
  a034=(a034+a021);
  if (res[0]!=0) res[0][7]=a034;
  a034=1.;
  if (res[1]!=0) res[1][0]=a034;
  if (res[1]!=0) res[1][1]=a034;
  if (res[1]!=0) res[1][2]=a034;
  if (res[1]!=0) res[1][3]=a034;
  if (res[1]!=0) res[1][4]=a034;
  if (res[1]!=0) res[1][5]=a034;
  if (res[1]!=0) res[1][6]=a034;
  a022=(a022/a017);
  a016=(a016+a016);
  a017=(a009+a009);
  a034=(a005/a015);
  a034=(a017*a034);
  a034=(a016*a034);
  a020=(a020+a020);
  a096=(a019+a019);
  a097=(a002/a014);
  a097=(a096*a097);
  a097=(a020*a097);
  a034=(a034-a097);
  a034=(a022*a034);
  a033=(a033/a031);
  a030=(a030+a030);
  a031=(a027+a027);
  a097=(a005/a029);
  a097=(a031*a097);
  a097=(a030*a097);
  a032=(a032+a032);
  a098=(a023+a023);
  a099=(a002/a028);
  a099=(a098*a099);
  a099=(a032*a099);
  a097=(a097-a099);
  a097=(a033*a097);
  a034=(a034+a097);
  a045=(a045/a043);
  a042=(a042+a042);
  a043=(a039+a039);
  a097=(a005/a041);
  a097=(a043*a097);
  a097=(a042*a097);
  a044=(a044+a044);
  a099=(a035+a035);
  a100=(a002/a040);
  a100=(a099*a100);
  a100=(a044*a100);
  a097=(a097-a100);
  a097=(a045*a097);
  a034=(a034+a097);
  a056=(a056/a054);
  a053=(a053+a053);
  a054=(a050+a050);
  a097=(a005/a052);
  a097=(a054*a097);
  a097=(a053*a097);
  a055=(a055+a055);
  a100=(a046+a046);
  a101=(a002/a051);
  a101=(a100*a101);
  a101=(a055*a101);
  a097=(a097-a101);
  a097=(a056*a097);
  a034=(a034+a097);
  a067=(a067/a065);
  a064=(a064+a064);
  a065=(a061+a061);
  a097=(a005/a063);
  a097=(a065*a097);
  a097=(a064*a097);
  a066=(a066+a066);
  a101=(a057+a057);
  a102=(a002/a062);
  a102=(a101*a102);
  a102=(a066*a102);
  a097=(a097-a102);
  a097=(a067*a097);
  a034=(a034+a097);
  a078=(a078/a076);
  a075=(a075+a075);
  a076=(a072+a072);
  a097=(a005/a074);
  a097=(a076*a097);
  a097=(a075*a097);
  a077=(a077+a077);
  a102=(a068+a068);
  a103=(a002/a073);
  a103=(a102*a103);
  a103=(a077*a103);
  a097=(a097-a103);
  a097=(a078*a097);
  a034=(a034+a097);
  a089=(a089/a087);
  a086=(a086+a086);
  a087=(a083+a083);
  a097=(a005/a085);
  a097=(a087*a097);
  a097=(a086*a097);
  a088=(a088+a088);
  a103=(a079+a079);
  a104=(a002/a084);
  a104=(a103*a104);
  a104=(a088*a104);
  a097=(a097-a104);
  a097=(a089*a097);
  a034=(a034+a097);
  a021=(a021/a095);
  a094=(a094+a094);
  a095=(a092+a092);
  a097=(a005/a010);
  a097=(a095*a097);
  a097=(a094*a097);
  a000=(a000+a000);
  a104=(a093+a093);
  a105=(a002/a004);
  a105=(a104*a105);
  a105=(a000*a105);
  a097=(a097-a105);
  a097=(a021*a097);
  a034=(a034+a097);
  a034=(-a034);
  if (res[1]!=0) res[1][7]=a034;
  a034=(a002/a015);
  a034=(a017*a034);
  a034=(a016*a034);
  a097=(a005/a014);
  a097=(a096*a097);
  a097=(a020*a097);
  a034=(a034+a097);
  a034=(a022*a034);
  a097=(a002/a029);
  a097=(a031*a097);
  a097=(a030*a097);
  a105=(a005/a028);
  a105=(a098*a105);
  a105=(a032*a105);
  a097=(a097+a105);
  a097=(a033*a097);
  a034=(a034+a097);
  a097=(a002/a041);
  a097=(a043*a097);
  a097=(a042*a097);
  a105=(a005/a040);
  a105=(a099*a105);
  a105=(a044*a105);
  a097=(a097+a105);
  a097=(a045*a097);
  a034=(a034+a097);
  a097=(a002/a052);
  a097=(a054*a097);
  a097=(a053*a097);
  a105=(a005/a051);
  a105=(a100*a105);
  a105=(a055*a105);
  a097=(a097+a105);
  a097=(a056*a097);
  a034=(a034+a097);
  a097=(a002/a063);
  a097=(a065*a097);
  a097=(a064*a097);
  a105=(a005/a062);
  a105=(a101*a105);
  a105=(a066*a105);
  a097=(a097+a105);
  a097=(a067*a097);
  a034=(a034+a097);
  a097=(a002/a074);
  a097=(a076*a097);
  a097=(a075*a097);
  a105=(a005/a073);
  a105=(a102*a105);
  a105=(a077*a105);
  a097=(a097+a105);
  a097=(a078*a097);
  a034=(a034+a097);
  a097=(a002/a085);
  a097=(a087*a097);
  a097=(a086*a097);
  a105=(a005/a084);
  a105=(a103*a105);
  a105=(a088*a105);
  a097=(a097+a105);
  a097=(a089*a097);
  a034=(a034+a097);
  a002=(a002/a010);
  a002=(a095*a002);
  a002=(a094*a002);
  a005=(a005/a004);
  a005=(a104*a005);
  a005=(a000*a005);
  a002=(a002+a005);
  a002=(a021*a002);
  a034=(a034+a002);
  a034=(-a034);
  if (res[1]!=0) res[1][8]=a034;
  a007=(a007/a015);
  a007=(a017*a007);
  a007=(a016*a007);
  a008=(a008+a006);
  a008=(a008/a014);
  a008=(a096*a008);
  a008=(a020*a008);
  a007=(a007-a008);
  a007=(a022*a007);
  a025=(a025/a029);
  a025=(a031*a025);
  a025=(a030*a025);
  a026=(a026+a024);
  a026=(a026/a028);
  a026=(a098*a026);
  a026=(a032*a026);
  a025=(a025-a026);
  a025=(a033*a025);
  a007=(a007+a025);
  a037=(a037/a041);
  a037=(a043*a037);
  a037=(a042*a037);
  a038=(a038+a036);
  a038=(a038/a040);
  a038=(a099*a038);
  a038=(a044*a038);
  a037=(a037-a038);
  a037=(a045*a037);
  a007=(a007+a037);
  a048=(a048/a052);
  a048=(a054*a048);
  a048=(a053*a048);
  a049=(a049+a047);
  a049=(a049/a051);
  a049=(a100*a049);
  a049=(a055*a049);
  a048=(a048-a049);
  a048=(a056*a048);
  a007=(a007+a048);
  a059=(a059/a063);
  a059=(a065*a059);
  a059=(a064*a059);
  a060=(a060+a058);
  a060=(a060/a062);
  a060=(a101*a060);
  a060=(a066*a060);
  a059=(a059-a060);
  a059=(a067*a059);
  a007=(a007+a059);
  a070=(a070/a074);
  a070=(a076*a070);
  a070=(a075*a070);
  a071=(a071+a069);
  a071=(a071/a073);
  a071=(a102*a071);
  a071=(a077*a071);
  a070=(a070-a071);
  a070=(a078*a070);
  a007=(a007+a070);
  a081=(a081/a085);
  a081=(a087*a081);
  a081=(a086*a081);
  a082=(a082+a080);
  a082=(a082/a084);
  a082=(a103*a082);
  a082=(a088*a082);
  a081=(a081-a082);
  a081=(a089*a081);
  a007=(a007+a081);
  a001=(a001/a010);
  a001=(a095*a001);
  a001=(a094*a001);
  a091=(a091+a090);
  a091=(a091/a004);
  a091=(a104*a091);
  a091=(a000*a091);
  a001=(a001-a091);
  a001=(a021*a001);
  a007=(a007+a001);
  a007=(-a007);
  if (res[1]!=0) res[1][9]=a007;
  a009=(a009/a015);
  a015=(a013<=a011);
  a013=(a011<=a013);
  a013=(a015+a013);
  a015=(a015/a013);
  a003=casadi_sign(a003);
  a011=(a011*a003);
  a015=(a015*a011);
  a009=(a009*a015);
  a017=(a017*a009);
  a016=(a016*a017);
  a019=(a019/a014);
  a014=(a012<=a018);
  a012=(a018<=a012);
  a012=(a014+a012);
  a014=(a014/a012);
  a018=(a018*a003);
  a014=(a014*a018);
  a019=(a019*a014);
  a096=(a096*a019);
  a020=(a020*a096);
  a016=(a016+a020);
  a022=(a022*a016);
  a027=(a027/a029);
  a027=(a027*a015);
  a031=(a031*a027);
  a030=(a030*a031);
  a023=(a023/a028);
  a023=(a023*a014);
  a098=(a098*a023);
  a032=(a032*a098);
  a030=(a030+a032);
  a033=(a033*a030);
  a022=(a022+a033);
  a039=(a039/a041);
  a039=(a039*a015);
  a043=(a043*a039);
  a042=(a042*a043);
  a035=(a035/a040);
  a035=(a035*a014);
  a099=(a099*a035);
  a044=(a044*a099);
  a042=(a042+a044);
  a045=(a045*a042);
  a022=(a022+a045);
  a050=(a050/a052);
  a050=(a050*a015);
  a054=(a054*a050);
  a053=(a053*a054);
  a046=(a046/a051);
  a046=(a046*a014);
  a100=(a100*a046);
  a055=(a055*a100);
  a053=(a053+a055);
  a056=(a056*a053);
  a022=(a022+a056);
  a061=(a061/a063);
  a061=(a061*a015);
  a065=(a065*a061);
  a064=(a064*a065);
  a057=(a057/a062);
  a057=(a057*a014);
  a101=(a101*a057);
  a066=(a066*a101);
  a064=(a064+a066);
  a067=(a067*a064);
  a022=(a022+a067);
  a072=(a072/a074);
  a072=(a072*a015);
  a076=(a076*a072);
  a075=(a075*a076);
  a068=(a068/a073);
  a068=(a068*a014);
  a102=(a102*a068);
  a077=(a077*a102);
  a075=(a075+a077);
  a078=(a078*a075);
  a022=(a022+a078);
  a083=(a083/a085);
  a083=(a083*a015);
  a087=(a087*a083);
  a086=(a086*a087);
  a079=(a079/a084);
  a079=(a079*a014);
  a103=(a103*a079);
  a088=(a088*a103);
  a086=(a086+a088);
  a089=(a089*a086);
  a022=(a022+a089);
  a092=(a092/a010);
  a092=(a092*a015);
  a095=(a095*a092);
  a094=(a094*a095);
  a093=(a093/a004);
  a093=(a093*a014);
  a104=(a104*a093);
  a000=(a000*a104);
  a094=(a094+a000);
  a021=(a021*a094);
  a022=(a022+a021);
  if (res[1]!=0) res[1][10]=a022;
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int spin_model_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int spin_model_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real spin_model_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* spin_model_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* spin_model_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* spin_model_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* spin_model_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
