/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) spin_model_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {6, 1, 1};
static const casadi_int casadi_s5[3] = {8, 1, 1};
static const casadi_int casadi_s6[21] = 
  {7, 8, 0, 1, 2, 3, 4, 5,
  6, 7, 10, 2, 3, 4, 5, 6,
  0, 1, 2, 3, 4};
static const casadi_int casadi_s7[3] = {8, 0, 1};

/* spin_model_cost_y_fun_jac_ut_xt:(i0[5],i1[2],i2[0],i3[],i4[6])->(o0[8],o1[7x8,10nz],o2[8x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33;
  a00=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a02;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a03=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a03;
  a03=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][5]=a03;
  a03=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][6]=a03;
  a03=arg[4]? arg[4][0] : 0;
  a03=(a00-a03);
  a04=cos(a02);
  a05=(a03*a04);
  a06=arg[4]? arg[4][1] : 0;
  a06=(a01-a06);
  a02=sin(a02);
  a07=(a06*a02);
  a08=(a05+a07);
  a09=8.0000000000000004e-01;
  a08=(a08/a09);
  a10=casadi_sq(a08);
  a11=casadi_sq(a10);
  a06=(a06*a04);
  a03=(a03*a02);
  a06=(a06-a03);
  a03=5.0000000000000000e-01;
  a12=(a06/a03);
  a13=casadi_sq(a12);
  a14=casadi_sq(a13);
  a11=(a11+a14);
  a14=1.0000000000000000e-04;
  a11=(a11+a14);
  a15=(1./a11);
  a16=arg[4]? arg[4][2] : 0;
  a16=(a00-a16);
  a17=(a16*a04);
  a18=arg[4]? arg[4][3] : 0;
  a18=(a01-a18);
  a19=(a18*a02);
  a20=(a17+a19);
  a20=(a20/a09);
  a21=casadi_sq(a20);
  a22=casadi_sq(a21);
  a18=(a18*a04);
  a16=(a16*a02);
  a18=(a18-a16);
  a16=(a18/a03);
  a23=casadi_sq(a16);
  a24=casadi_sq(a23);
  a22=(a22+a24);
  a22=(a22+a14);
  a24=(1./a22);
  a25=(a15+a24);
  a26=arg[4]? arg[4][4] : 0;
  a00=(a00-a26);
  a26=(a00*a04);
  a27=arg[4]? arg[4][5] : 0;
  a01=(a01-a27);
  a27=(a01*a02);
  a28=(a26+a27);
  a28=(a28/a09);
  a09=casadi_sq(a28);
  a29=casadi_sq(a09);
  a01=(a01*a04);
  a00=(a00*a02);
  a01=(a01-a00);
  a03=(a01/a03);
  a00=casadi_sq(a03);
  a30=casadi_sq(a00);
  a29=(a29+a30);
  a29=(a29+a14);
  a14=(1./a29);
  a25=(a25+a14);
  if (res[0]!=0) res[0][7]=a25;
  a25=1.;
  if (res[1]!=0) res[1][0]=a25;
  if (res[1]!=0) res[1][1]=a25;
  if (res[1]!=0) res[1][2]=a25;
  if (res[1]!=0) res[1][3]=a25;
  if (res[1]!=0) res[1][4]=a25;
  if (res[1]!=0) res[1][5]=a25;
  if (res[1]!=0) res[1][6]=a25;
  a15=(a15/a11);
  a10=(a10+a10);
  a08=(a08+a08);
  a11=1.2500000000000000e+00;
  a25=(a11*a04);
  a30=(a08*a25);
  a30=(a10*a30);
  a13=(a13+a13);
  a12=(a12+a12);
  a31=2.;
  a32=(a31*a02);
  a33=(a12*a32);
  a33=(a13*a33);
  a30=(a30-a33);
  a30=(a15*a30);
  a24=(a24/a22);
  a21=(a21+a21);
  a20=(a20+a20);
  a22=(a20*a25);
  a22=(a21*a22);
  a23=(a23+a23);
  a16=(a16+a16);
  a33=(a16*a32);
  a33=(a23*a33);
  a22=(a22-a33);
  a22=(a24*a22);
  a30=(a30+a22);
  a14=(a14/a29);
  a09=(a09+a09);
  a28=(a28+a28);
  a25=(a28*a25);
  a25=(a09*a25);
  a00=(a00+a00);
  a03=(a03+a03);
  a32=(a03*a32);
  a32=(a00*a32);
  a25=(a25-a32);
  a25=(a14*a25);
  a30=(a30+a25);
  a30=(-a30);
  if (res[1]!=0) res[1][7]=a30;
  a02=(a11*a02);
  a30=(a08*a02);
  a30=(a10*a30);
  a04=(a31*a04);
  a25=(a12*a04);
  a25=(a13*a25);
  a30=(a30+a25);
  a30=(a15*a30);
  a25=(a20*a02);
  a25=(a21*a25);
  a32=(a16*a04);
  a32=(a23*a32);
  a25=(a25+a32);
  a25=(a24*a25);
  a30=(a30+a25);
  a02=(a28*a02);
  a02=(a09*a02);
  a04=(a03*a04);
  a04=(a00*a04);
  a02=(a02+a04);
  a02=(a14*a02);
  a30=(a30+a02);
  a30=(-a30);
  if (res[1]!=0) res[1][8]=a30;
  a06=(a11*a06);
  a08=(a08*a06);
  a10=(a10*a08);
  a07=(a07+a05);
  a07=(a31*a07);
  a12=(a12*a07);
  a13=(a13*a12);
  a10=(a10-a13);
  a15=(a15*a10);
  a18=(a11*a18);
  a20=(a20*a18);
  a21=(a21*a20);
  a19=(a19+a17);
  a19=(a31*a19);
  a16=(a16*a19);
  a23=(a23*a16);
  a21=(a21-a23);
  a24=(a24*a21);
  a15=(a15+a24);
  a11=(a11*a01);
  a28=(a28*a11);
  a09=(a09*a28);
  a27=(a27+a26);
  a31=(a31*a27);
  a03=(a03*a31);
  a00=(a00*a03);
  a09=(a09-a00);
  a14=(a14*a09);
  a15=(a15+a14);
  a15=(-a15);
  if (res[1]!=0) res[1][9]=a15;
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int spin_model_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int spin_model_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real spin_model_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* spin_model_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* spin_model_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* spin_model_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* spin_model_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
