/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) spin_model_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {30, 1, 1};
static const casadi_int casadi_s5[3] = {8, 1, 1};
static const casadi_int casadi_s6[21] = 
  {7, 8, 0, 1, 2, 3, 4, 5,
  6, 7, 10, 2, 3, 4, 5, 6,
  0, 1, 2, 3, 4};
static const casadi_int casadi_s7[3] = {8, 0, 1};

/* spin_model_cost_y_0_fun_jac_ut_xt:(i0[5],i1[2],i2[0],i3[],i4[30])->(o0[8],o1[7x8,10nz],o2[8x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102, a103, a104, a105, a106, a107;
  casadi_real a108, a109, a110, a111, a112, a113;
  a000=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a000;
  a001=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a001;
  a002=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a002;
  a003=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a003;
  a003=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a003;
  a003=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][5]=a003;
  a003=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][6]=a003;
  a003=arg[4]? arg[4][0] : 0;
  a003=(a000-a003);
  a004=cos(a002);
  a005=(a003*a004);
  a006=arg[4]? arg[4][1] : 0;
  a006=(a001-a006);
  a002=sin(a002);
  a007=(a006*a002);
  a008=(a005+a007);
  a009=5.9999999999999998e-01;
  a010=arg[4]? arg[4][2] : 0;
  a011=(a009+a010);
  a008=(a008/a011);
  a012=casadi_sq(a008);
  a013=casadi_sq(a012);
  a006=(a006*a004);
  a003=(a003*a002);
  a006=(a006-a003);
  a003=5.0000000000000000e-01;
  a010=(a003+a010);
  a014=(a006/a010);
  a015=casadi_sq(a014);
  a016=casadi_sq(a015);
  a013=(a013+a016);
  a016=1.0000000000000000e-04;
  a013=(a013+a016);
  a017=(1./a013);
  a018=arg[4]? arg[4][3] : 0;
  a018=(a000-a018);
  a019=(a018*a004);
  a020=arg[4]? arg[4][4] : 0;
  a020=(a001-a020);
  a021=(a020*a002);
  a022=(a019+a021);
  a023=arg[4]? arg[4][5] : 0;
  a024=(a009+a023);
  a022=(a022/a024);
  a025=casadi_sq(a022);
  a026=casadi_sq(a025);
  a020=(a020*a004);
  a018=(a018*a002);
  a020=(a020-a018);
  a023=(a003+a023);
  a018=(a020/a023);
  a027=casadi_sq(a018);
  a028=casadi_sq(a027);
  a026=(a026+a028);
  a026=(a026+a016);
  a028=(1./a026);
  a029=(a017+a028);
  a030=arg[4]? arg[4][6] : 0;
  a030=(a000-a030);
  a031=(a030*a004);
  a032=arg[4]? arg[4][7] : 0;
  a032=(a001-a032);
  a033=(a032*a002);
  a034=(a031+a033);
  a035=arg[4]? arg[4][8] : 0;
  a036=(a009+a035);
  a034=(a034/a036);
  a037=casadi_sq(a034);
  a038=casadi_sq(a037);
  a032=(a032*a004);
  a030=(a030*a002);
  a032=(a032-a030);
  a035=(a003+a035);
  a030=(a032/a035);
  a039=casadi_sq(a030);
  a040=casadi_sq(a039);
  a038=(a038+a040);
  a038=(a038+a016);
  a040=(1./a038);
  a029=(a029+a040);
  a041=arg[4]? arg[4][9] : 0;
  a041=(a000-a041);
  a042=(a041*a004);
  a043=arg[4]? arg[4][10] : 0;
  a043=(a001-a043);
  a044=(a043*a002);
  a045=(a042+a044);
  a046=arg[4]? arg[4][11] : 0;
  a047=(a009+a046);
  a045=(a045/a047);
  a048=casadi_sq(a045);
  a049=casadi_sq(a048);
  a043=(a043*a004);
  a041=(a041*a002);
  a043=(a043-a041);
  a046=(a003+a046);
  a041=(a043/a046);
  a050=casadi_sq(a041);
  a051=casadi_sq(a050);
  a049=(a049+a051);
  a049=(a049+a016);
  a051=(1./a049);
  a029=(a029+a051);
  a052=arg[4]? arg[4][12] : 0;
  a052=(a000-a052);
  a053=(a052*a004);
  a054=arg[4]? arg[4][13] : 0;
  a054=(a001-a054);
  a055=(a054*a002);
  a056=(a053+a055);
  a057=arg[4]? arg[4][14] : 0;
  a058=(a009+a057);
  a056=(a056/a058);
  a059=casadi_sq(a056);
  a060=casadi_sq(a059);
  a054=(a054*a004);
  a052=(a052*a002);
  a054=(a054-a052);
  a057=(a003+a057);
  a052=(a054/a057);
  a061=casadi_sq(a052);
  a062=casadi_sq(a061);
  a060=(a060+a062);
  a060=(a060+a016);
  a062=(1./a060);
  a029=(a029+a062);
  a063=arg[4]? arg[4][15] : 0;
  a063=(a000-a063);
  a064=(a063*a004);
  a065=arg[4]? arg[4][16] : 0;
  a065=(a001-a065);
  a066=(a065*a002);
  a067=(a064+a066);
  a068=arg[4]? arg[4][17] : 0;
  a069=(a009+a068);
  a067=(a067/a069);
  a070=casadi_sq(a067);
  a071=casadi_sq(a070);
  a065=(a065*a004);
  a063=(a063*a002);
  a065=(a065-a063);
  a068=(a003+a068);
  a063=(a065/a068);
  a072=casadi_sq(a063);
  a073=casadi_sq(a072);
  a071=(a071+a073);
  a071=(a071+a016);
  a073=(1./a071);
  a029=(a029+a073);
  a074=arg[4]? arg[4][18] : 0;
  a074=(a000-a074);
  a075=(a074*a004);
  a076=arg[4]? arg[4][19] : 0;
  a076=(a001-a076);
  a077=(a076*a002);
  a078=(a075+a077);
  a079=arg[4]? arg[4][20] : 0;
  a080=(a009+a079);
  a078=(a078/a080);
  a081=casadi_sq(a078);
  a082=casadi_sq(a081);
  a076=(a076*a004);
  a074=(a074*a002);
  a076=(a076-a074);
  a079=(a003+a079);
  a074=(a076/a079);
  a083=casadi_sq(a074);
  a084=casadi_sq(a083);
  a082=(a082+a084);
  a082=(a082+a016);
  a084=(1./a082);
  a029=(a029+a084);
  a085=arg[4]? arg[4][21] : 0;
  a085=(a000-a085);
  a086=(a085*a004);
  a087=arg[4]? arg[4][22] : 0;
  a087=(a001-a087);
  a088=(a087*a002);
  a089=(a086+a088);
  a090=arg[4]? arg[4][23] : 0;
  a091=(a009+a090);
  a089=(a089/a091);
  a092=casadi_sq(a089);
  a093=casadi_sq(a092);
  a087=(a087*a004);
  a085=(a085*a002);
  a087=(a087-a085);
  a090=(a003+a090);
  a085=(a087/a090);
  a094=casadi_sq(a085);
  a095=casadi_sq(a094);
  a093=(a093+a095);
  a093=(a093+a016);
  a095=(1./a093);
  a029=(a029+a095);
  a096=arg[4]? arg[4][24] : 0;
  a096=(a000-a096);
  a097=(a096*a004);
  a098=arg[4]? arg[4][25] : 0;
  a098=(a001-a098);
  a099=(a098*a002);
  a100=(a097+a099);
  a101=arg[4]? arg[4][26] : 0;
  a102=(a009+a101);
  a100=(a100/a102);
  a103=casadi_sq(a100);
  a104=casadi_sq(a103);
  a098=(a098*a004);
  a096=(a096*a002);
  a098=(a098-a096);
  a101=(a003+a101);
  a096=(a098/a101);
  a105=casadi_sq(a096);
  a106=casadi_sq(a105);
  a104=(a104+a106);
  a104=(a104+a016);
  a106=(1./a104);
  a029=(a029+a106);
  a107=arg[4]? arg[4][27] : 0;
  a000=(a000-a107);
  a107=(a000*a004);
  a108=arg[4]? arg[4][28] : 0;
  a001=(a001-a108);
  a108=(a001*a002);
  a109=(a107+a108);
  a110=arg[4]? arg[4][29] : 0;
  a009=(a009+a110);
  a109=(a109/a009);
  a111=casadi_sq(a109);
  a112=casadi_sq(a111);
  a001=(a001*a004);
  a000=(a000*a002);
  a001=(a001-a000);
  a003=(a003+a110);
  a110=(a001/a003);
  a000=casadi_sq(a110);
  a113=casadi_sq(a000);
  a112=(a112+a113);
  a112=(a112+a016);
  a016=(1./a112);
  a029=(a029+a016);
  if (res[0]!=0) res[0][7]=a029;
  a029=1.;
  if (res[1]!=0) res[1][0]=a029;
  if (res[1]!=0) res[1][1]=a029;
  if (res[1]!=0) res[1][2]=a029;
  if (res[1]!=0) res[1][3]=a029;
  if (res[1]!=0) res[1][4]=a029;
  if (res[1]!=0) res[1][5]=a029;
  if (res[1]!=0) res[1][6]=a029;
  a017=(a017/a013);
  a012=(a012+a012);
  a008=(a008+a008);
  a013=(a004/a011);
  a013=(a008*a013);
  a013=(a012*a013);
  a015=(a015+a015);
  a014=(a014+a014);
  a029=(a002/a010);
  a029=(a014*a029);
  a029=(a015*a029);
  a013=(a013-a029);
  a013=(a017*a013);
  a028=(a028/a026);
  a025=(a025+a025);
  a022=(a022+a022);
  a026=(a004/a024);
  a026=(a022*a026);
  a026=(a025*a026);
  a027=(a027+a027);
  a018=(a018+a018);
  a029=(a002/a023);
  a029=(a018*a029);
  a029=(a027*a029);
  a026=(a026-a029);
  a026=(a028*a026);
  a013=(a013+a026);
  a040=(a040/a038);
  a037=(a037+a037);
  a034=(a034+a034);
  a038=(a004/a036);
  a038=(a034*a038);
  a038=(a037*a038);
  a039=(a039+a039);
  a030=(a030+a030);
  a026=(a002/a035);
  a026=(a030*a026);
  a026=(a039*a026);
  a038=(a038-a026);
  a038=(a040*a038);
  a013=(a013+a038);
  a051=(a051/a049);
  a048=(a048+a048);
  a045=(a045+a045);
  a049=(a004/a047);
  a049=(a045*a049);
  a049=(a048*a049);
  a050=(a050+a050);
  a041=(a041+a041);
  a038=(a002/a046);
  a038=(a041*a038);
  a038=(a050*a038);
  a049=(a049-a038);
  a049=(a051*a049);
  a013=(a013+a049);
  a062=(a062/a060);
  a059=(a059+a059);
  a056=(a056+a056);
  a060=(a004/a058);
  a060=(a056*a060);
  a060=(a059*a060);
  a061=(a061+a061);
  a052=(a052+a052);
  a049=(a002/a057);
  a049=(a052*a049);
  a049=(a061*a049);
  a060=(a060-a049);
  a060=(a062*a060);
  a013=(a013+a060);
  a073=(a073/a071);
  a070=(a070+a070);
  a067=(a067+a067);
  a071=(a004/a069);
  a071=(a067*a071);
  a071=(a070*a071);
  a072=(a072+a072);
  a063=(a063+a063);
  a060=(a002/a068);
  a060=(a063*a060);
  a060=(a072*a060);
  a071=(a071-a060);
  a071=(a073*a071);
  a013=(a013+a071);
  a084=(a084/a082);
  a081=(a081+a081);
  a078=(a078+a078);
  a082=(a004/a080);
  a082=(a078*a082);
  a082=(a081*a082);
  a083=(a083+a083);
  a074=(a074+a074);
  a071=(a002/a079);
  a071=(a074*a071);
  a071=(a083*a071);
  a082=(a082-a071);
  a082=(a084*a082);
  a013=(a013+a082);
  a095=(a095/a093);
  a092=(a092+a092);
  a089=(a089+a089);
  a093=(a004/a091);
  a093=(a089*a093);
  a093=(a092*a093);
  a094=(a094+a094);
  a085=(a085+a085);
  a082=(a002/a090);
  a082=(a085*a082);
  a082=(a094*a082);
  a093=(a093-a082);
  a093=(a095*a093);
  a013=(a013+a093);
  a106=(a106/a104);
  a103=(a103+a103);
  a100=(a100+a100);
  a104=(a004/a102);
  a104=(a100*a104);
  a104=(a103*a104);
  a105=(a105+a105);
  a096=(a096+a096);
  a093=(a002/a101);
  a093=(a096*a093);
  a093=(a105*a093);
  a104=(a104-a093);
  a104=(a106*a104);
  a013=(a013+a104);
  a016=(a016/a112);
  a111=(a111+a111);
  a109=(a109+a109);
  a112=(a004/a009);
  a112=(a109*a112);
  a112=(a111*a112);
  a000=(a000+a000);
  a110=(a110+a110);
  a104=(a002/a003);
  a104=(a110*a104);
  a104=(a000*a104);
  a112=(a112-a104);
  a112=(a016*a112);
  a013=(a013+a112);
  a013=(-a013);
  if (res[1]!=0) res[1][7]=a013;
  a013=(a002/a011);
  a013=(a008*a013);
  a013=(a012*a013);
  a112=(a004/a010);
  a112=(a014*a112);
  a112=(a015*a112);
  a013=(a013+a112);
  a013=(a017*a013);
  a112=(a002/a024);
  a112=(a022*a112);
  a112=(a025*a112);
  a104=(a004/a023);
  a104=(a018*a104);
  a104=(a027*a104);
  a112=(a112+a104);
  a112=(a028*a112);
  a013=(a013+a112);
  a112=(a002/a036);
  a112=(a034*a112);
  a112=(a037*a112);
  a104=(a004/a035);
  a104=(a030*a104);
  a104=(a039*a104);
  a112=(a112+a104);
  a112=(a040*a112);
  a013=(a013+a112);
  a112=(a002/a047);
  a112=(a045*a112);
  a112=(a048*a112);
  a104=(a004/a046);
  a104=(a041*a104);
  a104=(a050*a104);
  a112=(a112+a104);
  a112=(a051*a112);
  a013=(a013+a112);
  a112=(a002/a058);
  a112=(a056*a112);
  a112=(a059*a112);
  a104=(a004/a057);
  a104=(a052*a104);
  a104=(a061*a104);
  a112=(a112+a104);
  a112=(a062*a112);
  a013=(a013+a112);
  a112=(a002/a069);
  a112=(a067*a112);
  a112=(a070*a112);
  a104=(a004/a068);
  a104=(a063*a104);
  a104=(a072*a104);
  a112=(a112+a104);
  a112=(a073*a112);
  a013=(a013+a112);
  a112=(a002/a080);
  a112=(a078*a112);
  a112=(a081*a112);
  a104=(a004/a079);
  a104=(a074*a104);
  a104=(a083*a104);
  a112=(a112+a104);
  a112=(a084*a112);
  a013=(a013+a112);
  a112=(a002/a091);
  a112=(a089*a112);
  a112=(a092*a112);
  a104=(a004/a090);
  a104=(a085*a104);
  a104=(a094*a104);
  a112=(a112+a104);
  a112=(a095*a112);
  a013=(a013+a112);
  a112=(a002/a102);
  a112=(a100*a112);
  a112=(a103*a112);
  a104=(a004/a101);
  a104=(a096*a104);
  a104=(a105*a104);
  a112=(a112+a104);
  a112=(a106*a112);
  a013=(a013+a112);
  a002=(a002/a009);
  a002=(a109*a002);
  a002=(a111*a002);
  a004=(a004/a003);
  a004=(a110*a004);
  a004=(a000*a004);
  a002=(a002+a004);
  a002=(a016*a002);
  a013=(a013+a002);
  a013=(-a013);
  if (res[1]!=0) res[1][8]=a013;
  a006=(a006/a011);
  a008=(a008*a006);
  a012=(a012*a008);
  a007=(a007+a005);
  a007=(a007/a010);
  a014=(a014*a007);
  a015=(a015*a014);
  a012=(a012-a015);
  a017=(a017*a012);
  a020=(a020/a024);
  a022=(a022*a020);
  a025=(a025*a022);
  a021=(a021+a019);
  a021=(a021/a023);
  a018=(a018*a021);
  a027=(a027*a018);
  a025=(a025-a027);
  a028=(a028*a025);
  a017=(a017+a028);
  a032=(a032/a036);
  a034=(a034*a032);
  a037=(a037*a034);
  a033=(a033+a031);
  a033=(a033/a035);
  a030=(a030*a033);
  a039=(a039*a030);
  a037=(a037-a039);
  a040=(a040*a037);
  a017=(a017+a040);
  a043=(a043/a047);
  a045=(a045*a043);
  a048=(a048*a045);
  a044=(a044+a042);
  a044=(a044/a046);
  a041=(a041*a044);
  a050=(a050*a041);
  a048=(a048-a050);
  a051=(a051*a048);
  a017=(a017+a051);
  a054=(a054/a058);
  a056=(a056*a054);
  a059=(a059*a056);
  a055=(a055+a053);
  a055=(a055/a057);
  a052=(a052*a055);
  a061=(a061*a052);
  a059=(a059-a061);
  a062=(a062*a059);
  a017=(a017+a062);
  a065=(a065/a069);
  a067=(a067*a065);
  a070=(a070*a067);
  a066=(a066+a064);
  a066=(a066/a068);
  a063=(a063*a066);
  a072=(a072*a063);
  a070=(a070-a072);
  a073=(a073*a070);
  a017=(a017+a073);
  a076=(a076/a080);
  a078=(a078*a076);
  a081=(a081*a078);
  a077=(a077+a075);
  a077=(a077/a079);
  a074=(a074*a077);
  a083=(a083*a074);
  a081=(a081-a083);
  a084=(a084*a081);
  a017=(a017+a084);
  a087=(a087/a091);
  a089=(a089*a087);
  a092=(a092*a089);
  a088=(a088+a086);
  a088=(a088/a090);
  a085=(a085*a088);
  a094=(a094*a085);
  a092=(a092-a094);
  a095=(a095*a092);
  a017=(a017+a095);
  a098=(a098/a102);
  a100=(a100*a098);
  a103=(a103*a100);
  a099=(a099+a097);
  a099=(a099/a101);
  a096=(a096*a099);
  a105=(a105*a096);
  a103=(a103-a105);
  a106=(a106*a103);
  a017=(a017+a106);
  a001=(a001/a009);
  a109=(a109*a001);
  a111=(a111*a109);
  a108=(a108+a107);
  a108=(a108/a003);
  a110=(a110*a108);
  a000=(a000*a110);
  a111=(a111-a000);
  a016=(a016*a111);
  a017=(a017+a016);
  a017=(-a017);
  if (res[1]!=0) res[1][9]=a017;
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int spin_model_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int spin_model_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real spin_model_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* spin_model_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* spin_model_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* spin_model_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* spin_model_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
