/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) spin_model_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};
static const casadi_int casadi_s5[3] = {6, 1, 1};
static const casadi_int casadi_s6[19] = 
  {7, 7, 0, 0, 0, 3, 6, 9,
  9, 9, 2, 3, 4, 2, 3, 4,
  2, 3, 4};

/* spin_model_cost_y_hess:(i0[5],i1[2],i2[0],i3[8],i4[],i5[6])->(o0[7x7,9nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61;
  a00=arg[0]? arg[0][2] : 0;
  a01=sin(a00);
  a02=2.;
  a03=arg[0]? arg[0][1] : 0;
  a04=arg[5]? arg[5][5] : 0;
  a04=(a03-a04);
  a00=cos(a00);
  a05=(a04*a00);
  a06=arg[0]? arg[0][0] : 0;
  a07=arg[5]? arg[5][4] : 0;
  a07=(a06-a07);
  a08=(a07*a01);
  a05=(a05-a08);
  a08=5.0000000000000000e-01;
  a09=(a05/a08);
  a10=casadi_sq(a09);
  a11=(a10+a10);
  a12=(a07*a00);
  a13=(a04*a01);
  a14=(a12+a13);
  a15=8.0000000000000004e-01;
  a14=(a14/a15);
  a16=casadi_sq(a14);
  a17=casadi_sq(a16);
  a10=casadi_sq(a10);
  a17=(a17+a10);
  a10=1.0000000000000000e-04;
  a17=(a17+a10);
  a18=(1./a17);
  a18=(a18/a17);
  a19=arg[3]? arg[3][7] : 0;
  a20=(a18*a19);
  a21=(a11*a20);
  a22=(a02*a01);
  a23=(a22+a22);
  a24=(a21*a23);
  a09=(a09+a09);
  a25=(a09*a22);
  a26=(a25+a25);
  a26=(a20*a26);
  a16=(a16+a16);
  a14=(a14+a14);
  a27=1.2500000000000000e+00;
  a28=(a27*a00);
  a29=(a14*a28);
  a30=(a16*a29);
  a25=(a11*a25);
  a30=(a30-a25);
  a25=(a18*a30);
  a25=(a25/a17);
  a31=(a18/a17);
  a30=(a31*a30);
  a25=(a25+a30);
  a25=(a19*a25);
  a30=(a11*a25);
  a26=(a26+a30);
  a26=(a09*a26);
  a24=(a24+a26);
  a24=(a02*a24);
  a24=(a01*a24);
  a26=(a16*a20);
  a30=(a28+a28);
  a32=(a26*a30);
  a29=(a29+a29);
  a29=(a20*a29);
  a25=(a16*a25);
  a29=(a29-a25);
  a29=(a14*a29);
  a32=(a32+a29);
  a32=(a27*a32);
  a32=(a00*a32);
  a24=(a24+a32);
  a32=arg[5]? arg[5][3] : 0;
  a32=(a03-a32);
  a29=(a32*a00);
  a25=arg[5]? arg[5][2] : 0;
  a25=(a06-a25);
  a33=(a25*a01);
  a29=(a29-a33);
  a33=(a29/a08);
  a34=casadi_sq(a33);
  a35=(a34+a34);
  a36=(a25*a00);
  a37=(a32*a01);
  a38=(a36+a37);
  a38=(a38/a15);
  a39=casadi_sq(a38);
  a40=casadi_sq(a39);
  a34=casadi_sq(a34);
  a40=(a40+a34);
  a40=(a40+a10);
  a34=(1./a40);
  a34=(a34/a40);
  a41=(a34*a19);
  a42=(a35*a41);
  a43=(a42*a23);
  a33=(a33+a33);
  a44=(a33*a22);
  a45=(a44+a44);
  a45=(a41*a45);
  a39=(a39+a39);
  a38=(a38+a38);
  a46=(a38*a28);
  a47=(a39*a46);
  a44=(a35*a44);
  a47=(a47-a44);
  a44=(a34*a47);
  a44=(a44/a40);
  a48=(a34/a40);
  a47=(a48*a47);
  a44=(a44+a47);
  a44=(a19*a44);
  a47=(a35*a44);
  a45=(a45+a47);
  a45=(a33*a45);
  a43=(a43+a45);
  a43=(a02*a43);
  a43=(a01*a43);
  a45=(a39*a41);
  a47=(a45*a30);
  a46=(a46+a46);
  a46=(a41*a46);
  a44=(a39*a44);
  a46=(a46-a44);
  a46=(a38*a46);
  a47=(a47+a46);
  a47=(a27*a47);
  a47=(a00*a47);
  a43=(a43+a47);
  a24=(a24+a43);
  a43=arg[5]? arg[5][1] : 0;
  a03=(a03-a43);
  a43=(a03*a00);
  a47=arg[5]? arg[5][0] : 0;
  a06=(a06-a47);
  a47=(a06*a01);
  a43=(a43-a47);
  a08=(a43/a08);
  a47=casadi_sq(a08);
  a46=(a47+a47);
  a44=(a06*a00);
  a49=(a03*a01);
  a50=(a44+a49);
  a50=(a50/a15);
  a15=casadi_sq(a50);
  a51=casadi_sq(a15);
  a47=casadi_sq(a47);
  a51=(a51+a47);
  a51=(a51+a10);
  a10=(1./a51);
  a10=(a10/a51);
  a47=(a10*a19);
  a52=(a46*a47);
  a23=(a52*a23);
  a08=(a08+a08);
  a22=(a08*a22);
  a53=(a22+a22);
  a53=(a47*a53);
  a15=(a15+a15);
  a50=(a50+a50);
  a28=(a50*a28);
  a54=(a15*a28);
  a22=(a46*a22);
  a54=(a54-a22);
  a22=(a10*a54);
  a22=(a22/a51);
  a55=(a10/a51);
  a54=(a55*a54);
  a22=(a22+a54);
  a22=(a19*a22);
  a54=(a46*a22);
  a53=(a53+a54);
  a53=(a08*a53);
  a23=(a23+a53);
  a23=(a02*a23);
  a23=(a01*a23);
  a53=(a15*a47);
  a30=(a53*a30);
  a28=(a28+a28);
  a28=(a47*a28);
  a22=(a15*a22);
  a28=(a28-a22);
  a28=(a50*a28);
  a30=(a30+a28);
  a30=(a27*a30);
  a30=(a00*a30);
  a23=(a23+a30);
  a24=(a24+a23);
  a24=(-a24);
  if (res[0]!=0) res[0][0]=a24;
  a24=(a02*a00);
  a23=(a24+a24);
  a30=(a21*a23);
  a28=(a09*a24);
  a22=(a28+a28);
  a22=(a20*a22);
  a54=(a27*a01);
  a56=(a14*a54);
  a57=(a16*a56);
  a28=(a11*a28);
  a57=(a57+a28);
  a28=(a18*a57);
  a28=(a28/a17);
  a57=(a31*a57);
  a28=(a28+a57);
  a28=(a19*a28);
  a57=(a11*a28);
  a22=(a22-a57);
  a22=(a09*a22);
  a30=(a30+a22);
  a30=(a02*a30);
  a22=(a01*a30);
  a57=(a54+a54);
  a58=(a26*a57);
  a56=(a56+a56);
  a56=(a20*a56);
  a28=(a16*a28);
  a56=(a56-a28);
  a56=(a14*a56);
  a58=(a58+a56);
  a58=(a27*a58);
  a56=(a00*a58);
  a22=(a22-a56);
  a56=(a42*a23);
  a28=(a33*a24);
  a59=(a28+a28);
  a59=(a41*a59);
  a60=(a38*a54);
  a61=(a39*a60);
  a28=(a35*a28);
  a61=(a61+a28);
  a28=(a34*a61);
  a28=(a28/a40);
  a61=(a48*a61);
  a28=(a28+a61);
  a28=(a19*a28);
  a61=(a35*a28);
  a59=(a59-a61);
  a59=(a33*a59);
  a56=(a56+a59);
  a56=(a02*a56);
  a59=(a01*a56);
  a61=(a45*a57);
  a60=(a60+a60);
  a60=(a41*a60);
  a28=(a39*a28);
  a60=(a60-a28);
  a60=(a38*a60);
  a61=(a61+a60);
  a61=(a27*a61);
  a60=(a00*a61);
  a59=(a59-a60);
  a22=(a22+a59);
  a23=(a52*a23);
  a24=(a08*a24);
  a59=(a24+a24);
  a59=(a47*a59);
  a54=(a50*a54);
  a60=(a15*a54);
  a24=(a46*a24);
  a60=(a60+a24);
  a24=(a10*a60);
  a24=(a24/a51);
  a60=(a55*a60);
  a24=(a24+a60);
  a24=(a19*a24);
  a60=(a46*a24);
  a59=(a59-a60);
  a59=(a08*a59);
  a23=(a23+a59);
  a23=(a02*a23);
  a59=(a01*a23);
  a57=(a53*a57);
  a54=(a54+a54);
  a54=(a47*a54);
  a24=(a15*a24);
  a54=(a54-a24);
  a54=(a50*a54);
  a57=(a57+a54);
  a57=(a27*a57);
  a54=(a00*a57);
  a59=(a59-a54);
  a22=(a22+a59);
  if (res[0]!=0) res[0][1]=a22;
  a59=(a09*a21);
  a59=(a02*a59);
  a54=(a59*a00);
  a13=(a13+a12);
  a13=(a02*a13);
  a12=(a13+a13);
  a21=(a21*a12);
  a13=(a09*a13);
  a12=(a13+a13);
  a12=(a20*a12);
  a05=(a27*a05);
  a24=(a14*a05);
  a60=(a16*a24);
  a13=(a11*a13);
  a60=(a60-a13);
  a18=(a18*a60);
  a18=(a18/a17);
  a31=(a31*a60);
  a18=(a18+a31);
  a18=(a19*a18);
  a11=(a11*a18);
  a12=(a12+a11);
  a09=(a09*a12);
  a21=(a21+a09);
  a21=(a02*a21);
  a09=(a01*a21);
  a54=(a54-a09);
  a05=(a05+a05);
  a05=(a26*a05);
  a24=(a24+a24);
  a20=(a20*a24);
  a16=(a16*a18);
  a20=(a20-a16);
  a20=(a14*a20);
  a05=(a05+a20);
  a05=(a27*a05);
  a20=(a00*a05);
  a14=(a14*a26);
  a14=(a27*a14);
  a26=(a14*a01);
  a20=(a20-a26);
  a54=(a54-a20);
  a20=(a33*a42);
  a20=(a02*a20);
  a26=(a20*a00);
  a37=(a37+a36);
  a37=(a02*a37);
  a36=(a37+a37);
  a42=(a42*a36);
  a37=(a33*a37);
  a36=(a37+a37);
  a36=(a41*a36);
  a29=(a27*a29);
  a16=(a38*a29);
  a18=(a39*a16);
  a37=(a35*a37);
  a18=(a18-a37);
  a34=(a34*a18);
  a34=(a34/a40);
  a48=(a48*a18);
  a34=(a34+a48);
  a34=(a19*a34);
  a35=(a35*a34);
  a36=(a36+a35);
  a33=(a33*a36);
  a42=(a42+a33);
  a42=(a02*a42);
  a33=(a01*a42);
  a26=(a26-a33);
  a29=(a29+a29);
  a29=(a45*a29);
  a16=(a16+a16);
  a41=(a41*a16);
  a39=(a39*a34);
  a41=(a41-a39);
  a41=(a38*a41);
  a29=(a29+a41);
  a29=(a27*a29);
  a41=(a00*a29);
  a38=(a38*a45);
  a38=(a27*a38);
  a45=(a38*a01);
  a41=(a41-a45);
  a26=(a26-a41);
  a54=(a54+a26);
  a26=(a08*a52);
  a26=(a02*a26);
  a41=(a26*a00);
  a49=(a49+a44);
  a49=(a02*a49);
  a44=(a49+a49);
  a52=(a52*a44);
  a49=(a08*a49);
  a44=(a49+a49);
  a44=(a47*a44);
  a43=(a27*a43);
  a45=(a50*a43);
  a39=(a15*a45);
  a49=(a46*a49);
  a39=(a39-a49);
  a10=(a10*a39);
  a10=(a10/a51);
  a55=(a55*a39);
  a10=(a10+a55);
  a19=(a19*a10);
  a46=(a46*a19);
  a44=(a44+a46);
  a08=(a08*a44);
  a52=(a52+a08);
  a02=(a02*a52);
  a52=(a01*a02);
  a41=(a41-a52);
  a43=(a43+a43);
  a43=(a53*a43);
  a45=(a45+a45);
  a47=(a47*a45);
  a15=(a15*a19);
  a47=(a47-a15);
  a47=(a50*a47);
  a43=(a43+a47);
  a43=(a27*a43);
  a47=(a00*a43);
  a50=(a50*a53);
  a27=(a27*a50);
  a50=(a27*a01);
  a47=(a47-a50);
  a41=(a41-a47);
  a54=(a54+a41);
  if (res[0]!=0) res[0][2]=a54;
  if (res[0]!=0) res[0][3]=a22;
  a30=(a00*a30);
  a58=(a01*a58);
  a30=(a30+a58);
  a56=(a00*a56);
  a61=(a01*a61);
  a56=(a56+a61);
  a30=(a30+a56);
  a23=(a00*a23);
  a57=(a01*a57);
  a23=(a23+a57);
  a30=(a30+a23);
  a30=(-a30);
  if (res[0]!=0) res[0][4]=a30;
  a30=(a14*a00);
  a23=(a01*a05);
  a30=(a30+a23);
  a23=(a59*a01);
  a57=(a00*a21);
  a23=(a23+a57);
  a30=(a30-a23);
  a23=(a38*a00);
  a57=(a01*a29);
  a23=(a23+a57);
  a57=(a20*a01);
  a56=(a00*a42);
  a57=(a57+a56);
  a23=(a23-a57);
  a30=(a30+a23);
  a23=(a27*a00);
  a57=(a01*a43);
  a23=(a23+a57);
  a57=(a26*a01);
  a56=(a00*a02);
  a57=(a57+a56);
  a23=(a23-a57);
  a30=(a30+a23);
  a30=(-a30);
  if (res[0]!=0) res[0][5]=a30;
  if (res[0]!=0) res[0][6]=a54;
  if (res[0]!=0) res[0][7]=a30;
  a30=(a04*a59);
  a30=(a30*a00);
  a54=(a04*a21);
  a54=(a01*a54);
  a30=(a30-a54);
  a59=(a07*a59);
  a59=(a59*a01);
  a21=(a07*a21);
  a21=(a00*a21);
  a59=(a59+a21);
  a30=(a30-a59);
  a59=(a04*a05);
  a59=(a00*a59);
  a04=(a04*a14);
  a04=(a04*a01);
  a59=(a59-a04);
  a30=(a30-a59);
  a14=(a07*a14);
  a14=(a14*a00);
  a07=(a07*a05);
  a07=(a01*a07);
  a14=(a14+a07);
  a30=(a30+a14);
  a14=(a25*a20);
  a14=(a14*a01);
  a07=(a25*a42);
  a07=(a00*a07);
  a14=(a14+a07);
  a30=(a30-a14);
  a20=(a32*a20);
  a20=(a20*a00);
  a42=(a32*a42);
  a42=(a01*a42);
  a20=(a20-a42);
  a30=(a30+a20);
  a20=(a32*a29);
  a20=(a00*a20);
  a32=(a32*a38);
  a32=(a32*a01);
  a20=(a20-a32);
  a30=(a30-a20);
  a38=(a25*a38);
  a38=(a38*a00);
  a25=(a25*a29);
  a25=(a01*a25);
  a38=(a38+a25);
  a30=(a30+a38);
  a38=(a06*a26);
  a38=(a38*a01);
  a25=(a06*a02);
  a25=(a00*a25);
  a38=(a38+a25);
  a30=(a30-a38);
  a26=(a03*a26);
  a26=(a26*a00);
  a02=(a03*a02);
  a02=(a01*a02);
  a26=(a26-a02);
  a30=(a30+a26);
  a26=(a03*a43);
  a26=(a00*a26);
  a03=(a03*a27);
  a03=(a03*a01);
  a26=(a26-a03);
  a30=(a30-a26);
  a27=(a06*a27);
  a27=(a27*a00);
  a06=(a06*a43);
  a01=(a01*a06);
  a27=(a27+a01);
  a30=(a30+a27);
  if (res[0]!=0) res[0][8]=a30;
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int spin_model_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int spin_model_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real spin_model_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* spin_model_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* spin_model_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* spin_model_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    case 5: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* spin_model_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
