/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) spin_model_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {15, 1, 1};
static const casadi_int casadi_s5[3] = {8, 1, 1};
static const casadi_int casadi_s6[21] = 
  {7, 8, 0, 1, 2, 3, 4, 5,
  6, 7, 10, 2, 3, 4, 5, 6,
  0, 1, 2, 3, 4};
static const casadi_int casadi_s7[3] = {8, 0, 1};

/* spin_model_cost_y_fun_jac_ut_xt:(i0[5],i1[2],i2[0],i3[],i4[15])->(o0[8],o1[7x8,10nz],o2[8x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58;
  a00=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a02;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a03=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a03;
  a03=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][5]=a03;
  a03=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][6]=a03;
  a03=arg[4]? arg[4][0] : 0;
  a03=(a00-a03);
  a04=cos(a02);
  a05=(a03*a04);
  a06=arg[4]? arg[4][1] : 0;
  a06=(a01-a06);
  a02=sin(a02);
  a07=(a06*a02);
  a08=(a05+a07);
  a09=8.0000000000000004e-01;
  a10=arg[4]? arg[4][2] : 0;
  a11=(a09+a10);
  a08=(a08/a11);
  a12=casadi_sq(a08);
  a13=casadi_sq(a12);
  a06=(a06*a04);
  a03=(a03*a02);
  a06=(a06-a03);
  a03=5.0000000000000000e-01;
  a10=(a03+a10);
  a14=(a06/a10);
  a15=casadi_sq(a14);
  a16=casadi_sq(a15);
  a13=(a13+a16);
  a16=1.0000000000000000e-04;
  a13=(a13+a16);
  a17=(1./a13);
  a18=arg[4]? arg[4][3] : 0;
  a18=(a00-a18);
  a19=(a18*a04);
  a20=arg[4]? arg[4][4] : 0;
  a20=(a01-a20);
  a21=(a20*a02);
  a22=(a19+a21);
  a23=arg[4]? arg[4][5] : 0;
  a24=(a09+a23);
  a22=(a22/a24);
  a25=casadi_sq(a22);
  a26=casadi_sq(a25);
  a20=(a20*a04);
  a18=(a18*a02);
  a20=(a20-a18);
  a23=(a03+a23);
  a18=(a20/a23);
  a27=casadi_sq(a18);
  a28=casadi_sq(a27);
  a26=(a26+a28);
  a26=(a26+a16);
  a28=(1./a26);
  a29=(a17+a28);
  a30=arg[4]? arg[4][6] : 0;
  a30=(a00-a30);
  a31=(a30*a04);
  a32=arg[4]? arg[4][7] : 0;
  a32=(a01-a32);
  a33=(a32*a02);
  a34=(a31+a33);
  a35=arg[4]? arg[4][8] : 0;
  a36=(a09+a35);
  a34=(a34/a36);
  a37=casadi_sq(a34);
  a38=casadi_sq(a37);
  a32=(a32*a04);
  a30=(a30*a02);
  a32=(a32-a30);
  a35=(a03+a35);
  a30=(a32/a35);
  a39=casadi_sq(a30);
  a40=casadi_sq(a39);
  a38=(a38+a40);
  a38=(a38+a16);
  a40=(1./a38);
  a29=(a29+a40);
  a41=arg[4]? arg[4][9] : 0;
  a41=(a00-a41);
  a42=(a41*a04);
  a43=arg[4]? arg[4][10] : 0;
  a43=(a01-a43);
  a44=(a43*a02);
  a45=(a42+a44);
  a46=arg[4]? arg[4][11] : 0;
  a47=(a09+a46);
  a45=(a45/a47);
  a48=casadi_sq(a45);
  a49=casadi_sq(a48);
  a43=(a43*a04);
  a41=(a41*a02);
  a43=(a43-a41);
  a46=(a03+a46);
  a41=(a43/a46);
  a50=casadi_sq(a41);
  a51=casadi_sq(a50);
  a49=(a49+a51);
  a49=(a49+a16);
  a51=(1./a49);
  a29=(a29+a51);
  a52=arg[4]? arg[4][12] : 0;
  a00=(a00-a52);
  a52=(a00*a04);
  a53=arg[4]? arg[4][13] : 0;
  a01=(a01-a53);
  a53=(a01*a02);
  a54=(a52+a53);
  a55=arg[4]? arg[4][14] : 0;
  a09=(a09+a55);
  a54=(a54/a09);
  a56=casadi_sq(a54);
  a57=casadi_sq(a56);
  a01=(a01*a04);
  a00=(a00*a02);
  a01=(a01-a00);
  a03=(a03+a55);
  a55=(a01/a03);
  a00=casadi_sq(a55);
  a58=casadi_sq(a00);
  a57=(a57+a58);
  a57=(a57+a16);
  a16=(1./a57);
  a29=(a29+a16);
  if (res[0]!=0) res[0][7]=a29;
  a29=1.;
  if (res[1]!=0) res[1][0]=a29;
  if (res[1]!=0) res[1][1]=a29;
  if (res[1]!=0) res[1][2]=a29;
  if (res[1]!=0) res[1][3]=a29;
  if (res[1]!=0) res[1][4]=a29;
  if (res[1]!=0) res[1][5]=a29;
  if (res[1]!=0) res[1][6]=a29;
  a17=(a17/a13);
  a12=(a12+a12);
  a08=(a08+a08);
  a13=(a04/a11);
  a13=(a08*a13);
  a13=(a12*a13);
  a15=(a15+a15);
  a14=(a14+a14);
  a29=(a02/a10);
  a29=(a14*a29);
  a29=(a15*a29);
  a13=(a13-a29);
  a13=(a17*a13);
  a28=(a28/a26);
  a25=(a25+a25);
  a22=(a22+a22);
  a26=(a04/a24);
  a26=(a22*a26);
  a26=(a25*a26);
  a27=(a27+a27);
  a18=(a18+a18);
  a29=(a02/a23);
  a29=(a18*a29);
  a29=(a27*a29);
  a26=(a26-a29);
  a26=(a28*a26);
  a13=(a13+a26);
  a40=(a40/a38);
  a37=(a37+a37);
  a34=(a34+a34);
  a38=(a04/a36);
  a38=(a34*a38);
  a38=(a37*a38);
  a39=(a39+a39);
  a30=(a30+a30);
  a26=(a02/a35);
  a26=(a30*a26);
  a26=(a39*a26);
  a38=(a38-a26);
  a38=(a40*a38);
  a13=(a13+a38);
  a51=(a51/a49);
  a48=(a48+a48);
  a45=(a45+a45);
  a49=(a04/a47);
  a49=(a45*a49);
  a49=(a48*a49);
  a50=(a50+a50);
  a41=(a41+a41);
  a38=(a02/a46);
  a38=(a41*a38);
  a38=(a50*a38);
  a49=(a49-a38);
  a49=(a51*a49);
  a13=(a13+a49);
  a16=(a16/a57);
  a56=(a56+a56);
  a54=(a54+a54);
  a57=(a04/a09);
  a57=(a54*a57);
  a57=(a56*a57);
  a00=(a00+a00);
  a55=(a55+a55);
  a49=(a02/a03);
  a49=(a55*a49);
  a49=(a00*a49);
  a57=(a57-a49);
  a57=(a16*a57);
  a13=(a13+a57);
  a13=(-a13);
  if (res[1]!=0) res[1][7]=a13;
  a13=(a02/a11);
  a13=(a08*a13);
  a13=(a12*a13);
  a57=(a04/a10);
  a57=(a14*a57);
  a57=(a15*a57);
  a13=(a13+a57);
  a13=(a17*a13);
  a57=(a02/a24);
  a57=(a22*a57);
  a57=(a25*a57);
  a49=(a04/a23);
  a49=(a18*a49);
  a49=(a27*a49);
  a57=(a57+a49);
  a57=(a28*a57);
  a13=(a13+a57);
  a57=(a02/a36);
  a57=(a34*a57);
  a57=(a37*a57);
  a49=(a04/a35);
  a49=(a30*a49);
  a49=(a39*a49);
  a57=(a57+a49);
  a57=(a40*a57);
  a13=(a13+a57);
  a57=(a02/a47);
  a57=(a45*a57);
  a57=(a48*a57);
  a49=(a04/a46);
  a49=(a41*a49);
  a49=(a50*a49);
  a57=(a57+a49);
  a57=(a51*a57);
  a13=(a13+a57);
  a02=(a02/a09);
  a02=(a54*a02);
  a02=(a56*a02);
  a04=(a04/a03);
  a04=(a55*a04);
  a04=(a00*a04);
  a02=(a02+a04);
  a02=(a16*a02);
  a13=(a13+a02);
  a13=(-a13);
  if (res[1]!=0) res[1][8]=a13;
  a06=(a06/a11);
  a08=(a08*a06);
  a12=(a12*a08);
  a07=(a07+a05);
  a07=(a07/a10);
  a14=(a14*a07);
  a15=(a15*a14);
  a12=(a12-a15);
  a17=(a17*a12);
  a20=(a20/a24);
  a22=(a22*a20);
  a25=(a25*a22);
  a21=(a21+a19);
  a21=(a21/a23);
  a18=(a18*a21);
  a27=(a27*a18);
  a25=(a25-a27);
  a28=(a28*a25);
  a17=(a17+a28);
  a32=(a32/a36);
  a34=(a34*a32);
  a37=(a37*a34);
  a33=(a33+a31);
  a33=(a33/a35);
  a30=(a30*a33);
  a39=(a39*a30);
  a37=(a37-a39);
  a40=(a40*a37);
  a17=(a17+a40);
  a43=(a43/a47);
  a45=(a45*a43);
  a48=(a48*a45);
  a44=(a44+a42);
  a44=(a44/a46);
  a41=(a41*a44);
  a50=(a50*a41);
  a48=(a48-a50);
  a51=(a51*a48);
  a17=(a17+a51);
  a01=(a01/a09);
  a54=(a54*a01);
  a56=(a56*a54);
  a53=(a53+a52);
  a53=(a53/a03);
  a55=(a55*a53);
  a00=(a00*a55);
  a56=(a56-a00);
  a16=(a16*a56);
  a17=(a17+a16);
  a17=(-a17);
  if (res[1]!=0) res[1][9]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int spin_model_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int spin_model_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real spin_model_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* spin_model_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* spin_model_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* spin_model_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* spin_model_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
