/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) spin_model_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};
static const casadi_int casadi_s5[3] = {15, 1, 1};
static const casadi_int casadi_s6[19] = 
  {7, 7, 0, 0, 0, 3, 6, 9,
  9, 9, 2, 3, 4, 2, 3, 4,
  2, 3, 4};

/* spin_model_cost_y_hess:(i0[5],i1[2],i2[0],i3[8],i4[],i5[15])->(o0[7x7,9nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102;
  a000=arg[0]? arg[0][2] : 0;
  a001=sin(a000);
  a002=arg[0]? arg[0][1] : 0;
  a003=arg[5]? arg[5][13] : 0;
  a003=(a002-a003);
  a000=cos(a000);
  a004=(a003*a000);
  a005=arg[0]? arg[0][0] : 0;
  a006=arg[5]? arg[5][12] : 0;
  a006=(a005-a006);
  a007=(a006*a001);
  a004=(a004-a007);
  a007=5.0000000000000000e-01;
  a008=arg[5]? arg[5][14] : 0;
  a009=(a007+a008);
  a010=(a004/a009);
  a011=casadi_sq(a010);
  a012=(a011+a011);
  a013=(a006*a000);
  a014=(a003*a001);
  a015=(a013+a014);
  a016=8.0000000000000004e-01;
  a008=(a016+a008);
  a015=(a015/a008);
  a017=casadi_sq(a015);
  a018=casadi_sq(a017);
  a011=casadi_sq(a011);
  a018=(a018+a011);
  a011=1.0000000000000000e-04;
  a018=(a018+a011);
  a019=(1./a018);
  a019=(a019/a018);
  a020=arg[3]? arg[3][7] : 0;
  a021=(a019*a020);
  a022=(a012*a021);
  a023=(a001/a009);
  a024=(a023+a023);
  a024=(a022*a024);
  a010=(a010+a010);
  a023=(a010*a023);
  a025=(a023+a023);
  a025=(a021*a025);
  a017=(a017+a017);
  a015=(a015+a015);
  a026=(a000/a008);
  a027=(a015*a026);
  a028=(a017*a027);
  a023=(a012*a023);
  a028=(a028-a023);
  a023=(a019*a028);
  a023=(a023/a018);
  a029=(a019/a018);
  a028=(a029*a028);
  a023=(a023+a028);
  a023=(a020*a023);
  a028=(a012*a023);
  a025=(a025+a028);
  a025=(a010*a025);
  a024=(a024+a025);
  a024=(a024/a009);
  a024=(a001*a024);
  a025=(a017*a021);
  a026=(a026+a026);
  a026=(a025*a026);
  a027=(a027+a027);
  a027=(a021*a027);
  a023=(a017*a023);
  a027=(a027-a023);
  a027=(a015*a027);
  a026=(a026+a027);
  a026=(a026/a008);
  a026=(a000*a026);
  a024=(a024+a026);
  a026=arg[5]? arg[5][10] : 0;
  a026=(a002-a026);
  a027=(a026*a000);
  a023=arg[5]? arg[5][9] : 0;
  a023=(a005-a023);
  a028=(a023*a001);
  a027=(a027-a028);
  a028=arg[5]? arg[5][11] : 0;
  a030=(a007+a028);
  a031=(a027/a030);
  a032=casadi_sq(a031);
  a033=(a032+a032);
  a034=(a023*a000);
  a035=(a026*a001);
  a036=(a034+a035);
  a028=(a016+a028);
  a036=(a036/a028);
  a037=casadi_sq(a036);
  a038=casadi_sq(a037);
  a032=casadi_sq(a032);
  a038=(a038+a032);
  a038=(a038+a011);
  a032=(1./a038);
  a032=(a032/a038);
  a039=(a032*a020);
  a040=(a033*a039);
  a041=(a001/a030);
  a042=(a041+a041);
  a042=(a040*a042);
  a031=(a031+a031);
  a041=(a031*a041);
  a043=(a041+a041);
  a043=(a039*a043);
  a037=(a037+a037);
  a036=(a036+a036);
  a044=(a000/a028);
  a045=(a036*a044);
  a046=(a037*a045);
  a041=(a033*a041);
  a046=(a046-a041);
  a041=(a032*a046);
  a041=(a041/a038);
  a047=(a032/a038);
  a046=(a047*a046);
  a041=(a041+a046);
  a041=(a020*a041);
  a046=(a033*a041);
  a043=(a043+a046);
  a043=(a031*a043);
  a042=(a042+a043);
  a042=(a042/a030);
  a042=(a001*a042);
  a043=(a037*a039);
  a044=(a044+a044);
  a044=(a043*a044);
  a045=(a045+a045);
  a045=(a039*a045);
  a041=(a037*a041);
  a045=(a045-a041);
  a045=(a036*a045);
  a044=(a044+a045);
  a044=(a044/a028);
  a044=(a000*a044);
  a042=(a042+a044);
  a024=(a024+a042);
  a042=arg[5]? arg[5][7] : 0;
  a042=(a002-a042);
  a044=(a042*a000);
  a045=arg[5]? arg[5][6] : 0;
  a045=(a005-a045);
  a041=(a045*a001);
  a044=(a044-a041);
  a041=arg[5]? arg[5][8] : 0;
  a046=(a007+a041);
  a048=(a044/a046);
  a049=casadi_sq(a048);
  a050=(a049+a049);
  a051=(a045*a000);
  a052=(a042*a001);
  a053=(a051+a052);
  a041=(a016+a041);
  a053=(a053/a041);
  a054=casadi_sq(a053);
  a055=casadi_sq(a054);
  a049=casadi_sq(a049);
  a055=(a055+a049);
  a055=(a055+a011);
  a049=(1./a055);
  a049=(a049/a055);
  a056=(a049*a020);
  a057=(a050*a056);
  a058=(a001/a046);
  a059=(a058+a058);
  a059=(a057*a059);
  a048=(a048+a048);
  a058=(a048*a058);
  a060=(a058+a058);
  a060=(a056*a060);
  a054=(a054+a054);
  a053=(a053+a053);
  a061=(a000/a041);
  a062=(a053*a061);
  a063=(a054*a062);
  a058=(a050*a058);
  a063=(a063-a058);
  a058=(a049*a063);
  a058=(a058/a055);
  a064=(a049/a055);
  a063=(a064*a063);
  a058=(a058+a063);
  a058=(a020*a058);
  a063=(a050*a058);
  a060=(a060+a063);
  a060=(a048*a060);
  a059=(a059+a060);
  a059=(a059/a046);
  a059=(a001*a059);
  a060=(a054*a056);
  a061=(a061+a061);
  a061=(a060*a061);
  a062=(a062+a062);
  a062=(a056*a062);
  a058=(a054*a058);
  a062=(a062-a058);
  a062=(a053*a062);
  a061=(a061+a062);
  a061=(a061/a041);
  a061=(a000*a061);
  a059=(a059+a061);
  a024=(a024+a059);
  a059=arg[5]? arg[5][4] : 0;
  a059=(a002-a059);
  a061=(a059*a000);
  a062=arg[5]? arg[5][3] : 0;
  a062=(a005-a062);
  a058=(a062*a001);
  a061=(a061-a058);
  a058=arg[5]? arg[5][5] : 0;
  a063=(a007+a058);
  a065=(a061/a063);
  a066=casadi_sq(a065);
  a067=(a066+a066);
  a068=(a062*a000);
  a069=(a059*a001);
  a070=(a068+a069);
  a058=(a016+a058);
  a070=(a070/a058);
  a071=casadi_sq(a070);
  a072=casadi_sq(a071);
  a066=casadi_sq(a066);
  a072=(a072+a066);
  a072=(a072+a011);
  a066=(1./a072);
  a066=(a066/a072);
  a073=(a066*a020);
  a074=(a067*a073);
  a075=(a001/a063);
  a076=(a075+a075);
  a076=(a074*a076);
  a065=(a065+a065);
  a075=(a065*a075);
  a077=(a075+a075);
  a077=(a073*a077);
  a071=(a071+a071);
  a070=(a070+a070);
  a078=(a000/a058);
  a079=(a070*a078);
  a080=(a071*a079);
  a075=(a067*a075);
  a080=(a080-a075);
  a075=(a066*a080);
  a075=(a075/a072);
  a081=(a066/a072);
  a080=(a081*a080);
  a075=(a075+a080);
  a075=(a020*a075);
  a080=(a067*a075);
  a077=(a077+a080);
  a077=(a065*a077);
  a076=(a076+a077);
  a076=(a076/a063);
  a076=(a001*a076);
  a077=(a071*a073);
  a078=(a078+a078);
  a078=(a077*a078);
  a079=(a079+a079);
  a079=(a073*a079);
  a075=(a071*a075);
  a079=(a079-a075);
  a079=(a070*a079);
  a078=(a078+a079);
  a078=(a078/a058);
  a078=(a000*a078);
  a076=(a076+a078);
  a024=(a024+a076);
  a076=arg[5]? arg[5][1] : 0;
  a002=(a002-a076);
  a076=(a002*a000);
  a078=arg[5]? arg[5][0] : 0;
  a005=(a005-a078);
  a078=(a005*a001);
  a076=(a076-a078);
  a078=arg[5]? arg[5][2] : 0;
  a007=(a007+a078);
  a079=(a076/a007);
  a075=casadi_sq(a079);
  a080=(a075+a075);
  a082=(a005*a000);
  a083=(a002*a001);
  a084=(a082+a083);
  a016=(a016+a078);
  a084=(a084/a016);
  a078=casadi_sq(a084);
  a085=casadi_sq(a078);
  a075=casadi_sq(a075);
  a085=(a085+a075);
  a085=(a085+a011);
  a011=(1./a085);
  a011=(a011/a085);
  a075=(a011*a020);
  a086=(a080*a075);
  a087=(a001/a007);
  a088=(a087+a087);
  a088=(a086*a088);
  a079=(a079+a079);
  a087=(a079*a087);
  a089=(a087+a087);
  a089=(a075*a089);
  a078=(a078+a078);
  a084=(a084+a084);
  a090=(a000/a016);
  a091=(a084*a090);
  a092=(a078*a091);
  a087=(a080*a087);
  a092=(a092-a087);
  a087=(a011*a092);
  a087=(a087/a085);
  a093=(a011/a085);
  a092=(a093*a092);
  a087=(a087+a092);
  a087=(a020*a087);
  a092=(a080*a087);
  a089=(a089+a092);
  a089=(a079*a089);
  a088=(a088+a089);
  a088=(a088/a007);
  a088=(a001*a088);
  a089=(a078*a075);
  a090=(a090+a090);
  a090=(a089*a090);
  a091=(a091+a091);
  a091=(a075*a091);
  a087=(a078*a087);
  a091=(a091-a087);
  a091=(a084*a091);
  a090=(a090+a091);
  a090=(a090/a016);
  a090=(a000*a090);
  a088=(a088+a090);
  a024=(a024+a088);
  a024=(-a024);
  if (res[0]!=0) res[0][0]=a024;
  a024=(a000/a009);
  a088=(a024+a024);
  a088=(a022*a088);
  a024=(a010*a024);
  a090=(a024+a024);
  a090=(a021*a090);
  a091=(a001/a008);
  a087=(a015*a091);
  a092=(a017*a087);
  a024=(a012*a024);
  a092=(a092+a024);
  a024=(a019*a092);
  a024=(a024/a018);
  a092=(a029*a092);
  a024=(a024+a092);
  a024=(a020*a024);
  a092=(a012*a024);
  a090=(a090-a092);
  a090=(a010*a090);
  a088=(a088+a090);
  a088=(a088/a009);
  a090=(a001*a088);
  a091=(a091+a091);
  a091=(a025*a091);
  a087=(a087+a087);
  a087=(a021*a087);
  a024=(a017*a024);
  a087=(a087-a024);
  a087=(a015*a087);
  a091=(a091+a087);
  a091=(a091/a008);
  a087=(a000*a091);
  a090=(a090-a087);
  a087=(a000/a030);
  a024=(a087+a087);
  a024=(a040*a024);
  a087=(a031*a087);
  a092=(a087+a087);
  a092=(a039*a092);
  a094=(a001/a028);
  a095=(a036*a094);
  a096=(a037*a095);
  a087=(a033*a087);
  a096=(a096+a087);
  a087=(a032*a096);
  a087=(a087/a038);
  a096=(a047*a096);
  a087=(a087+a096);
  a087=(a020*a087);
  a096=(a033*a087);
  a092=(a092-a096);
  a092=(a031*a092);
  a024=(a024+a092);
  a024=(a024/a030);
  a092=(a001*a024);
  a094=(a094+a094);
  a094=(a043*a094);
  a095=(a095+a095);
  a095=(a039*a095);
  a087=(a037*a087);
  a095=(a095-a087);
  a095=(a036*a095);
  a094=(a094+a095);
  a094=(a094/a028);
  a095=(a000*a094);
  a092=(a092-a095);
  a090=(a090+a092);
  a092=(a000/a046);
  a095=(a092+a092);
  a095=(a057*a095);
  a092=(a048*a092);
  a087=(a092+a092);
  a087=(a056*a087);
  a096=(a001/a041);
  a097=(a053*a096);
  a098=(a054*a097);
  a092=(a050*a092);
  a098=(a098+a092);
  a092=(a049*a098);
  a092=(a092/a055);
  a098=(a064*a098);
  a092=(a092+a098);
  a092=(a020*a092);
  a098=(a050*a092);
  a087=(a087-a098);
  a087=(a048*a087);
  a095=(a095+a087);
  a095=(a095/a046);
  a087=(a001*a095);
  a096=(a096+a096);
  a096=(a060*a096);
  a097=(a097+a097);
  a097=(a056*a097);
  a092=(a054*a092);
  a097=(a097-a092);
  a097=(a053*a097);
  a096=(a096+a097);
  a096=(a096/a041);
  a097=(a000*a096);
  a087=(a087-a097);
  a090=(a090+a087);
  a087=(a000/a063);
  a097=(a087+a087);
  a097=(a074*a097);
  a087=(a065*a087);
  a092=(a087+a087);
  a092=(a073*a092);
  a098=(a001/a058);
  a099=(a070*a098);
  a100=(a071*a099);
  a087=(a067*a087);
  a100=(a100+a087);
  a087=(a066*a100);
  a087=(a087/a072);
  a100=(a081*a100);
  a087=(a087+a100);
  a087=(a020*a087);
  a100=(a067*a087);
  a092=(a092-a100);
  a092=(a065*a092);
  a097=(a097+a092);
  a097=(a097/a063);
  a092=(a001*a097);
  a098=(a098+a098);
  a098=(a077*a098);
  a099=(a099+a099);
  a099=(a073*a099);
  a087=(a071*a087);
  a099=(a099-a087);
  a099=(a070*a099);
  a098=(a098+a099);
  a098=(a098/a058);
  a099=(a000*a098);
  a092=(a092-a099);
  a090=(a090+a092);
  a092=(a000/a007);
  a099=(a092+a092);
  a099=(a086*a099);
  a092=(a079*a092);
  a087=(a092+a092);
  a087=(a075*a087);
  a100=(a001/a016);
  a101=(a084*a100);
  a102=(a078*a101);
  a092=(a080*a092);
  a102=(a102+a092);
  a092=(a011*a102);
  a092=(a092/a085);
  a102=(a093*a102);
  a092=(a092+a102);
  a092=(a020*a092);
  a102=(a080*a092);
  a087=(a087-a102);
  a087=(a079*a087);
  a099=(a099+a087);
  a099=(a099/a007);
  a087=(a001*a099);
  a100=(a100+a100);
  a100=(a089*a100);
  a101=(a101+a101);
  a101=(a075*a101);
  a092=(a078*a092);
  a101=(a101-a092);
  a101=(a084*a101);
  a100=(a100+a101);
  a100=(a100/a016);
  a101=(a000*a100);
  a087=(a087-a101);
  a090=(a090+a087);
  if (res[0]!=0) res[0][1]=a090;
  a087=(a010*a022);
  a087=(a087/a009);
  a101=(a087*a000);
  a014=(a014+a013);
  a014=(a014/a009);
  a013=(a014+a014);
  a022=(a022*a013);
  a014=(a010*a014);
  a013=(a014+a014);
  a013=(a021*a013);
  a004=(a004/a008);
  a092=(a015*a004);
  a102=(a017*a092);
  a014=(a012*a014);
  a102=(a102-a014);
  a019=(a019*a102);
  a019=(a019/a018);
  a029=(a029*a102);
  a019=(a019+a029);
  a019=(a020*a019);
  a012=(a012*a019);
  a013=(a013+a012);
  a010=(a010*a013);
  a022=(a022+a010);
  a022=(a022/a009);
  a009=(a001*a022);
  a101=(a101-a009);
  a004=(a004+a004);
  a004=(a025*a004);
  a092=(a092+a092);
  a021=(a021*a092);
  a017=(a017*a019);
  a021=(a021-a017);
  a021=(a015*a021);
  a004=(a004+a021);
  a004=(a004/a008);
  a021=(a000*a004);
  a015=(a015*a025);
  a015=(a015/a008);
  a008=(a015*a001);
  a021=(a021-a008);
  a101=(a101-a021);
  a021=(a031*a040);
  a021=(a021/a030);
  a008=(a021*a000);
  a035=(a035+a034);
  a035=(a035/a030);
  a034=(a035+a035);
  a040=(a040*a034);
  a035=(a031*a035);
  a034=(a035+a035);
  a034=(a039*a034);
  a027=(a027/a028);
  a025=(a036*a027);
  a017=(a037*a025);
  a035=(a033*a035);
  a017=(a017-a035);
  a032=(a032*a017);
  a032=(a032/a038);
  a047=(a047*a017);
  a032=(a032+a047);
  a032=(a020*a032);
  a033=(a033*a032);
  a034=(a034+a033);
  a031=(a031*a034);
  a040=(a040+a031);
  a040=(a040/a030);
  a030=(a001*a040);
  a008=(a008-a030);
  a027=(a027+a027);
  a027=(a043*a027);
  a025=(a025+a025);
  a039=(a039*a025);
  a037=(a037*a032);
  a039=(a039-a037);
  a039=(a036*a039);
  a027=(a027+a039);
  a027=(a027/a028);
  a039=(a000*a027);
  a036=(a036*a043);
  a036=(a036/a028);
  a028=(a036*a001);
  a039=(a039-a028);
  a008=(a008-a039);
  a101=(a101+a008);
  a008=(a048*a057);
  a008=(a008/a046);
  a039=(a008*a000);
  a052=(a052+a051);
  a052=(a052/a046);
  a051=(a052+a052);
  a057=(a057*a051);
  a052=(a048*a052);
  a051=(a052+a052);
  a051=(a056*a051);
  a044=(a044/a041);
  a028=(a053*a044);
  a043=(a054*a028);
  a052=(a050*a052);
  a043=(a043-a052);
  a049=(a049*a043);
  a049=(a049/a055);
  a064=(a064*a043);
  a049=(a049+a064);
  a049=(a020*a049);
  a050=(a050*a049);
  a051=(a051+a050);
  a048=(a048*a051);
  a057=(a057+a048);
  a057=(a057/a046);
  a046=(a001*a057);
  a039=(a039-a046);
  a044=(a044+a044);
  a044=(a060*a044);
  a028=(a028+a028);
  a056=(a056*a028);
  a054=(a054*a049);
  a056=(a056-a054);
  a056=(a053*a056);
  a044=(a044+a056);
  a044=(a044/a041);
  a056=(a000*a044);
  a053=(a053*a060);
  a053=(a053/a041);
  a041=(a053*a001);
  a056=(a056-a041);
  a039=(a039-a056);
  a101=(a101+a039);
  a039=(a065*a074);
  a039=(a039/a063);
  a056=(a039*a000);
  a069=(a069+a068);
  a069=(a069/a063);
  a068=(a069+a069);
  a074=(a074*a068);
  a069=(a065*a069);
  a068=(a069+a069);
  a068=(a073*a068);
  a061=(a061/a058);
  a041=(a070*a061);
  a060=(a071*a041);
  a069=(a067*a069);
  a060=(a060-a069);
  a066=(a066*a060);
  a066=(a066/a072);
  a081=(a081*a060);
  a066=(a066+a081);
  a066=(a020*a066);
  a067=(a067*a066);
  a068=(a068+a067);
  a065=(a065*a068);
  a074=(a074+a065);
  a074=(a074/a063);
  a063=(a001*a074);
  a056=(a056-a063);
  a061=(a061+a061);
  a061=(a077*a061);
  a041=(a041+a041);
  a073=(a073*a041);
  a071=(a071*a066);
  a073=(a073-a071);
  a073=(a070*a073);
  a061=(a061+a073);
  a061=(a061/a058);
  a073=(a000*a061);
  a070=(a070*a077);
  a070=(a070/a058);
  a058=(a070*a001);
  a073=(a073-a058);
  a056=(a056-a073);
  a101=(a101+a056);
  a056=(a079*a086);
  a056=(a056/a007);
  a073=(a056*a000);
  a083=(a083+a082);
  a083=(a083/a007);
  a082=(a083+a083);
  a086=(a086*a082);
  a083=(a079*a083);
  a082=(a083+a083);
  a082=(a075*a082);
  a076=(a076/a016);
  a058=(a084*a076);
  a077=(a078*a058);
  a083=(a080*a083);
  a077=(a077-a083);
  a011=(a011*a077);
  a011=(a011/a085);
  a093=(a093*a077);
  a011=(a011+a093);
  a020=(a020*a011);
  a080=(a080*a020);
  a082=(a082+a080);
  a079=(a079*a082);
  a086=(a086+a079);
  a086=(a086/a007);
  a007=(a001*a086);
  a073=(a073-a007);
  a076=(a076+a076);
  a076=(a089*a076);
  a058=(a058+a058);
  a075=(a075*a058);
  a078=(a078*a020);
  a075=(a075-a078);
  a075=(a084*a075);
  a076=(a076+a075);
  a076=(a076/a016);
  a075=(a000*a076);
  a084=(a084*a089);
  a084=(a084/a016);
  a016=(a084*a001);
  a075=(a075-a016);
  a073=(a073-a075);
  a101=(a101+a073);
  if (res[0]!=0) res[0][2]=a101;
  if (res[0]!=0) res[0][3]=a090;
  a088=(a000*a088);
  a091=(a001*a091);
  a088=(a088+a091);
  a024=(a000*a024);
  a094=(a001*a094);
  a024=(a024+a094);
  a088=(a088+a024);
  a095=(a000*a095);
  a096=(a001*a096);
  a095=(a095+a096);
  a088=(a088+a095);
  a097=(a000*a097);
  a098=(a001*a098);
  a097=(a097+a098);
  a088=(a088+a097);
  a099=(a000*a099);
  a100=(a001*a100);
  a099=(a099+a100);
  a088=(a088+a099);
  a088=(-a088);
  if (res[0]!=0) res[0][4]=a088;
  a088=(a015*a000);
  a099=(a001*a004);
  a088=(a088+a099);
  a099=(a087*a001);
  a100=(a000*a022);
  a099=(a099+a100);
  a088=(a088-a099);
  a099=(a036*a000);
  a100=(a001*a027);
  a099=(a099+a100);
  a100=(a021*a001);
  a097=(a000*a040);
  a100=(a100+a097);
  a099=(a099-a100);
  a088=(a088+a099);
  a099=(a053*a000);
  a100=(a001*a044);
  a099=(a099+a100);
  a100=(a008*a001);
  a097=(a000*a057);
  a100=(a100+a097);
  a099=(a099-a100);
  a088=(a088+a099);
  a099=(a070*a000);
  a100=(a001*a061);
  a099=(a099+a100);
  a100=(a039*a001);
  a097=(a000*a074);
  a100=(a100+a097);
  a099=(a099-a100);
  a088=(a088+a099);
  a099=(a084*a000);
  a100=(a001*a076);
  a099=(a099+a100);
  a100=(a056*a001);
  a097=(a000*a086);
  a100=(a100+a097);
  a099=(a099-a100);
  a088=(a088+a099);
  a088=(-a088);
  if (res[0]!=0) res[0][5]=a088;
  if (res[0]!=0) res[0][6]=a101;
  if (res[0]!=0) res[0][7]=a088;
  a088=(a003*a087);
  a088=(a088*a000);
  a101=(a003*a022);
  a101=(a001*a101);
  a088=(a088-a101);
  a087=(a006*a087);
  a087=(a087*a001);
  a022=(a006*a022);
  a022=(a000*a022);
  a087=(a087+a022);
  a088=(a088-a087);
  a087=(a003*a004);
  a087=(a000*a087);
  a003=(a003*a015);
  a003=(a003*a001);
  a087=(a087-a003);
  a088=(a088-a087);
  a015=(a006*a015);
  a015=(a015*a000);
  a006=(a006*a004);
  a006=(a001*a006);
  a015=(a015+a006);
  a088=(a088+a015);
  a015=(a023*a021);
  a015=(a015*a001);
  a006=(a023*a040);
  a006=(a000*a006);
  a015=(a015+a006);
  a088=(a088-a015);
  a021=(a026*a021);
  a021=(a021*a000);
  a040=(a026*a040);
  a040=(a001*a040);
  a021=(a021-a040);
  a088=(a088+a021);
  a021=(a026*a027);
  a021=(a000*a021);
  a026=(a026*a036);
  a026=(a026*a001);
  a021=(a021-a026);
  a088=(a088-a021);
  a036=(a023*a036);
  a036=(a036*a000);
  a023=(a023*a027);
  a023=(a001*a023);
  a036=(a036+a023);
  a088=(a088+a036);
  a036=(a045*a008);
  a036=(a036*a001);
  a023=(a045*a057);
  a023=(a000*a023);
  a036=(a036+a023);
  a088=(a088-a036);
  a008=(a042*a008);
  a008=(a008*a000);
  a057=(a042*a057);
  a057=(a001*a057);
  a008=(a008-a057);
  a088=(a088+a008);
  a008=(a042*a044);
  a008=(a000*a008);
  a042=(a042*a053);
  a042=(a042*a001);
  a008=(a008-a042);
  a088=(a088-a008);
  a053=(a045*a053);
  a053=(a053*a000);
  a045=(a045*a044);
  a045=(a001*a045);
  a053=(a053+a045);
  a088=(a088+a053);
  a053=(a062*a039);
  a053=(a053*a001);
  a045=(a062*a074);
  a045=(a000*a045);
  a053=(a053+a045);
  a088=(a088-a053);
  a039=(a059*a039);
  a039=(a039*a000);
  a074=(a059*a074);
  a074=(a001*a074);
  a039=(a039-a074);
  a088=(a088+a039);
  a039=(a059*a061);
  a039=(a000*a039);
  a059=(a059*a070);
  a059=(a059*a001);
  a039=(a039-a059);
  a088=(a088-a039);
  a070=(a062*a070);
  a070=(a070*a000);
  a062=(a062*a061);
  a062=(a001*a062);
  a070=(a070+a062);
  a088=(a088+a070);
  a070=(a005*a056);
  a070=(a070*a001);
  a062=(a005*a086);
  a062=(a000*a062);
  a070=(a070+a062);
  a088=(a088-a070);
  a056=(a002*a056);
  a056=(a056*a000);
  a086=(a002*a086);
  a086=(a001*a086);
  a056=(a056-a086);
  a088=(a088+a056);
  a056=(a002*a076);
  a056=(a000*a056);
  a002=(a002*a084);
  a002=(a002*a001);
  a056=(a056-a002);
  a088=(a088-a056);
  a084=(a005*a084);
  a084=(a084*a000);
  a005=(a005*a076);
  a001=(a001*a005);
  a084=(a084+a001);
  a088=(a088+a084);
  if (res[0]!=0) res[0][8]=a088;
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void spin_model_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int spin_model_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int spin_model_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real spin_model_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* spin_model_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* spin_model_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* spin_model_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    case 5: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* spin_model_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int spin_model_cost_y_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
